DROP TABLE IF EXISTS sales;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS partners;

CREATE TABLE partners (
    partner_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    inn VARCHAR(12) NOT NULL UNIQUE,
    contact_email VARCHAR(254) NOT NULL UNIQUE,
    phone VARCHAR(50),
    rating DECIMAL(2, 1),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_partners_inn
        CHECK (inn ~ '^[0-9]{10}([0-9]{2})?$'),
    CONSTRAINT chk_partners_rating
        CHECK (rating IS NULL OR rating BETWEEN 0 AND 5)
);

CREATE TABLE products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL UNIQUE,
    unit VARCHAR(20) NOT NULL DEFAULT 'шт.'
);

CREATE TABLE sales (
    sale_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    sale_date DATE NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(12, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sales_partner
        FOREIGN KEY (partner_id)
        REFERENCES partners (partner_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_sales_product
        FOREIGN KEY (product_id)
        REFERENCES products (product_id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_sales_quantity CHECK (quantity > 0),
    CONSTRAINT chk_sales_unit_price CHECK (unit_price >= 0)
);

CREATE INDEX idx_sales_partner_date ON sales (partner_id, sale_date);
